name: Simple CI

on:
    push:
        branches: [ develop, master ]
    pull_request:
        branches: [ develop, master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest
